# Generated by Django 3.2.5 on 2021-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_foodtypes_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userPhone', models.CharField(max_length=20)),
                ('userAdderss', models.CharField(max_length=100)),
                ('userImg', models.CharField(max_length=150)),
                ('userRank', models.IntegerField()),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='childcidname',
            field=models.CharField(max_length=50),
        ),
    ]
